# Generated by Django 2.2.1 on 2019-05-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190503_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(default='select your city', on_delete=django.db.models.deletion.CASCADE, to='city_and_state.City'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ownnershipstatus',
            field=models.CharField(default='normaluser', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.ForeignKey(default='select your state', on_delete=django.db.models.deletion.CASCADE, to='city_and_state.State'),
        ),
    ]
