# Generated by Django 2.2.1 on 2019-05-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190506_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='count',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
