# Generated by Django 2.2.1 on 2019-05-09 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0004_restaurant_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_type_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.CharField(max_length=30, null=True)),
                ('veg_or_nonveg', models.BooleanField(default='veg')),
                ('img', models.ImageField(default='default.png', upload_to='images/')),
                ('dishinfo', models.CharField(max_length=1024, null=True)),
                ('dish_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.DishesType')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
    ]
