# Generated by Django 2.2.1 on 2019-05-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20190509_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='veg_or_nonveg',
        ),
    ]
