# Generated by Django 2.2.1 on 2019-05-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_remove_dishes_veg_or_nonveg'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='veg_or_nonveg',
            field=models.CharField(default='veg', max_length=6),
            preserve_default=False,
        ),
    ]
