# Generated by Django 2.2.1 on 2019-05-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_dishes_veg_or_nonveg'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='price',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
