# Generated by Django 2.2.1 on 2019-05-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city_and_state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=30, null=True)),
                ('restaurantname', models.CharField(max_length=30, null=True)),
                ('bank_account_no', models.CharField(max_length=1024)),
                ('address', models.CharField(max_length=1024)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city_and_state.City')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city_and_state.State')),
            ],
        ),
    ]
