# Generated by Django 2.2.1 on 2019-05-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='flag',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
