# Generated by Django 2.2.1 on 2019-05-27 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderstatus', models.CharField(max_length=30, null=True)),
                ('totalpricetax', models.CharField(max_length=30, null=True)),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=30, null=True)),
                ('totalprice', models.CharField(max_length=30, null=True)),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.Dishes')),
                ('orders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart_and_orders.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryaddress', models.CharField(default=0, max_length=1000)),
                ('orders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart_and_orders.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=30, null=True)),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.Dishes')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
